Reverted back to A* and fixed error
spent many hours fixing this error 'estDistance = bottomCost - heuristic(nextPos[0], destination) + outwardsTarget[1] + heuristic(outwardsTarget[0], destination)
TypeError: unsupported operand type(s) for +: 'float' and 'tuple'' which is finally fixed. Used week 3 for reference